/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

/**
 *
 * @author imanudd
 */
public class supplier extends javax.swing.JFrame {

    /**
     * Creates new form supplier
     */
    Connection conn;
    ResultSet rs;
    Boolean status;
    repository.supplier repoSupplier = new repository.supplier();
    public supplier() {
        initComponents();
        connect();
        try {
            getDataSupplier();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private void connect(){
        conn = repository.config.initDB();
    }

    private void getDataSupplier() throws SQLException {
    rs = repoSupplier.getData(conn);

    int q = rs.getMetaData().getColumnCount();
    DefaultTableModel df = (DefaultTableModel)tbl_supplier.getModel();
    df.setRowCount(0);

    while(rs.next()){
        Vector v2 = new Vector();
        for (int i = 1; i<=q; i++){
            v2.add(rs.getInt("id"));
            v2.add(rs.getString("name"));
            v2.add(rs.getString("address"));
        }
        df.addRow(v2);
    }
    }

    private dto.supplier getDataTextBox(){
        dto.supplier supplier = new dto.supplier();
        supplier.setId(Integer.parseInt(txt_id.getText()));
        supplier.setName(txt_supplierName.getText());
        supplier.setAddress(txt_address.getText());

        return supplier;
    }

    private void clearData() {
        txt_address.setText("");
        txt_id.setText("");
        txt_supplierName.setText("");
    }

    private void addNewSupplier(){
        dto.supplier supplier = new dto.supplier();
        supplier.setName(txt_supplierName.getText());
        supplier.setAddress(txt_address.getText());
        status = repoSupplier.addNewSupplier(conn, supplier);

        if(!status){
            JOptionPane.showMessageDialog(null, "failed to add new supplier");
            return;
        }

        JOptionPane.showMessageDialog(null, "success to add new supplier");
        clearData();
        try {
            getDataSupplier();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private void updateSupplier(){
        dto.supplier supplier = getDataTextBox();
        status = repoSupplier.updateSupplier(conn, supplier);

        if(!status){
            JOptionPane.showMessageDialog(null, "failed to update supplier");
            return;
        }

        JOptionPane.showMessageDialog(null, "success to update supplier");
        clearData();
        try {
            getDataSupplier();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private void deleteSupplier(){
        dto.supplier supp = getDataTextBox();
        status = repoSupplier.delete(conn,supp.getId());

        if(!status){
            JOptionPane.showMessageDialog(null, "failed to delete supplier");
            return;
        }

        JOptionPane.showMessageDialog(null, "success to delete new supplier");
        clearData();
        try {
            getDataSupplier();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cashier = new javax.swing.JButton();
        transaction = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        supplier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        txt_supplierName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_supplier = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setForeground(new java.awt.Color(102, 204, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("PET");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel8.setIconTextGap(20);
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("STOP");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.setIconTextGap(20);
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 100));

        cashier.setBackground(new java.awt.Color(52, 73, 94));
        cashier.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cashier.setForeground(new java.awt.Color(255, 255, 255));
        cashier.setText("Cashiers");
        cashier.setBorder(null);
        cashier.setContentAreaFilled(false);
        cashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cashierMouseEntered(evt);
            }
        });
        cashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierActionPerformed(evt);
            }
        });

        transaction.setBackground(new java.awt.Color(52, 73, 94));
        transaction.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        transaction.setForeground(new java.awt.Color(255, 255, 255));
        transaction.setText("Transactions");
        transaction.setBorder(null);
        transaction.setBorderPainted(false);
        transaction.setContentAreaFilled(false);
        transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionActionPerformed(evt);
            }
        });

        inventory.setBackground(new java.awt.Color(52, 73, 94));
        inventory.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        inventory.setForeground(new java.awt.Color(255, 255, 255));
        inventory.setText("Stocks");
        inventory.setBorder(null);
        inventory.setContentAreaFilled(false);
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });

        supplier.setBackground(new java.awt.Color(52, 73, 94));
        supplier.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        supplier.setForeground(new java.awt.Color(255, 255, 255));
        supplier.setText("Suppliers");
        supplier.setBorder(null);
        supplier.setContentAreaFilled(false);
        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashier, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 100);

        jPanel2.setBackground(new java.awt.Color(149, 165, 166));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel2.setLayout(null);

        txt_id.setText("idsup");
        jPanel2.add(txt_id);
        txt_id.setBounds(200, 70, 110, 16);

        jLabel2.setText("Nama Supplier");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 110, 78, 16);

        jLabel3.setText("Alamat");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 150, 78, 16);
        jPanel2.add(txt_address);
        txt_address.setBounds(200, 150, 160, 22);
        jPanel2.add(txt_supplierName);
        txt_supplierName.setBounds(200, 110, 160, 22);

        tbl_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Supplier Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_supplier);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(480, 30, 452, 220);

        jLabel4.setText("ID supplier");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 70, 90, 16);

        btn_delete.setText("delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete);
        btn_delete.setBounds(150, 250, 160, 23);

        btn_add.setText("Insert new supplier");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add);
        btn_add.setBounds(60, 210, 160, 23);

        btn_update.setText("update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_update);
        btn_update.setBounds(240, 210, 160, 23);

        btn_back.setText("back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel2.add(btn_back);
        btn_back.setBounds(780, 290, 160, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 1000, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashierMouseEntered

    }//GEN-LAST:event_cashierMouseEntered

    private void cashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierActionPerformed
        this.setVisible(false);
        new cashier().setVisible(true);
    }//GEN-LAST:event_cashierActionPerformed

    private void transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionActionPerformed
        this.setVisible(false);
        new transaction().setVisible(true);
    }//GEN-LAST:event_transactionActionPerformed

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        product productPage = new product();
        productPage.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_inventoryActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        deleteSupplier();
        btn_add.setEnabled(true);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        addNewSupplier();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
       this.setEnabled(false);

       new home().setEnabled(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void tbl_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_supplierMouseClicked
        int row = tbl_supplier.getSelectedRow();
        txt_id.setText(tbl_supplier.getModel().getValueAt(row, 0).toString());
        txt_supplierName.setText(tbl_supplier.getModel().getValueAt(row, 1).toString());
        txt_address.setText(tbl_supplier.getModel().getValueAt(row, 2).toString());

        btn_add.setEnabled(false);
    }//GEN-LAST:event_tbl_supplierMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        updateSupplier();
        btn_add.setEnabled(true);
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton cashier;
    private javax.swing.JButton inventory;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton supplier;
    private javax.swing.JTable tbl_supplier;
    private javax.swing.JButton transaction;
    private javax.swing.JTextField txt_address;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_supplierName;
    // End of variables declaration//GEN-END:variables
}
